### ISSUE TITLE
showMessage With Sync

### ISSUE THREAD

**Issue by djimondev** [aonghusonia/sense-hat-led#11]
Hello,

It seems to be a problem by using the showMessage() method when sense-hat is required with sync.

the error is 
```
/home/pi/rpi-counter/node_modules/sense-hat-led/index.js:13
  usleep(s * 1000000);
  ^
```
const sense = require("sense-hat-led").sync;
sense.showMessage("test", [255,0,0], function() {});

Do you know how to fix it ? 
I need to use "sync" in order to put delays between messages to display

**Comment by aonghusonia** [comment]
you don't supply a callback to the synchronous methods so it should be:

```javascript
const sense = require("sense-hat-led").sync;
sense.showMessage("test", 0.1, [255,0,0]);
```
