### ISSUE TITLE
Deprecation Warning on showMessage async

### ISSUE THREAD

**Issue by GerryWilko** [aonghusonia/sense-hat-led#8]
`DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

This warning fills the console when using the async showMessage function, seems to be calling function without callback on each matrix update.

**Comment by aonghusonia** [comment]
Are you using node 7 I haven't tested it with that. Will upgrade & check it out tonight.

**Comment by GerryWilko** [comment]
Yes I am on 7. Apologies, should have stated that in the issue.

Thanks for the great package!

**Comment by aonghusonia** [comment]
I wasn't supplying a callback to fs.close.  Updated github. Give it  a try and if your errors are gone I'll update npm
